name: Build
on: 
  workflow_dispatch:
jobs: 
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - name: Get code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Building the application
        run: mvn clean install -DskipTests
      - name: Uploading Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: target/*.war

  mysecondjob:
    needs: myfirstjob
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye"