name: Build
on: workflow_dispatch

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - name: Get code
        uses: actions/checkout@v4
      - name : Installing Java 11
        uses: actions/setup-java@v4
        with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
      - name: Building application
        run: mvn clean install -DskipTests
    
  my_second_job:
     needs: my_first_job
     runs-on: ubuntu-latest
     steps:
       - run: echo "Hi"
