name: Build
on: workflow_dispatch

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
    
  my_second_job:
    needs: my_first_job
     runs-on: ubuntu-latest
     steps:
       - run: echo "Hi"
