name: deploy
on: 
 workflow_run: 
   workflows: ci build
   types: completed
jobs: 
   deploy: 
     environment: testing
     runs-on: ubuntu-latest
     steps: 
     - name: Download build artifact from triggered workflow
       uses: dawidd6/action-download-artifact@v2
       with:
          run_id: ${{ github.event.workflow_run.id }}
          # name: ${{ github.event.workflow_run.event.inputs.ARTIFACT_NAME }}
          path: ./artifacts
          search_artifacts: true
     - run: |
        cd artifacts
        cd */
        pwd
     - name: Deploying to Tomcat...
       run: curl -v -u ${{secrets.TOMCAT_USR}}:${{secrets.TOMCAT_PSW}} -T /home/runner/work/SpringContactApp/SpringContactApp/artifacts/*/*.war http://34.125.70.121:8080/manager/text/deploy?path=/spring-contact-app
