name: my-demo-github-actions
on: workflow_dispatch
  
jobs: 
   Build: 
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - name: Set up JDK 17 for x64
         uses: actions/setup-java@v3
         with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
       - name: building artifacts
         run: mvn package
       - run: ls
       - name: Step 3 - Use the Upload Artifact GitHub Action
         uses: actions/upload-artifact@v2
         with: 
             name: spring-contact-app
             path: target/*.war
       - name: deploy to Tomcat
         run: curl -v -u pradeep:pradeep -T /home/runner/work/SpringContactApp/SpringContactApp/target/SpringContactApp-1.0-SNAPSHOT.war http://34.125.220.76:8080/manager/text/deploy?path=/spring-contact-app
             
