name: my-demo-github-actions
on:
  push:
    branches: [ master ]
  
jobs: 
   Build: 
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - name: Set up JDK 17 for x64
         uses: actions/setup-java@v3
         with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
       - name: building artifacts
         run: mvn package
       - run: ls
             
